Note: Test that should ERROR - using variable after passing to takes parameter

Process called "takes_ownership" takes data as Integer returns Integer:
    Return data
End Process

Process called "main" returns Integer:
    Let x be 42

    Note: Pass x to function with takes parameter - x is moved
    Let result be takes_ownership(x)

    Note: ERROR: Cannot use x after it was moved via takes parameter
    print_integer(x)

    Return 0
End Process
